# Generated by Django 2.0.6 on 2018-07-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_img', models.CharField(blank=True, max_length=20, null=True, verbose_name='显示图标')),
                ('nav_text', models.CharField(max_length=100, verbose_name='显示文本')),
                ('nav_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='导航地址')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否可用')),
                ('orders', models.IntegerField(default=0, verbose_name='排序')),
                ('permission_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='权限编码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nav_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_sub', to='pages.Navigation', verbose_name='父导航栏')),
            ],
            options={
                'verbose_name': '导航栏',
                'verbose_name_plural': '导航栏',
                'ordering': ['orders'],
            },
        ),
    ]
