# Generated by Django 2.0.6 on 2018-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180717_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='images/pic.png', upload_to='images/%Y/%m', verbose_name='插图'),
        ),
    ]
