# Generated by Django 2.0.7 on 2018-08-08 07:37

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contents',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
    ]
