# Generated by Django 2.0.7 on 2018-09-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='昵称')),
                ('wechat_username', models.CharField(max_length=100, verbose_name='微信用户名')),
                ('realname', models.CharField(blank=True, max_length=100, null=True, verbose_name='真实姓名')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('user_tag', models.CharField(choices=[('0', '球员'), ('1', '球迷')], max_length=5, verbose_name='用户类型')),
                ('position', models.CharField(blank=True, choices=[('0', '球员'), ('1', '球迷')], max_length=5, null=True, verbose_name='常踢位置')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m', verbose_name='头像')),
            ],
            options={
                'verbose_name': '注册用户',
                'verbose_name_plural': '注册用户',
            },
        ),
    ]
