# Generated by Django 2.0.7 on 2018-09-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=100, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '真实用户姓名',
                'verbose_name_plural': '真实用户姓名',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('gk', '守门员'), ('sw', '清道夫'), ('cb', '中后卫'), ('lcb', '左中后卫'), ('rcb', '右中后卫'), ('lb', '左后卫'), ('rb', '右后卫'), ('lwb', '左边后卫'), ('rwb', '右边后卫'), ('dmf', '后腰'), ('swf', '边前卫'), ('lmf', '左边前卫'), ('rmf', '右边前卫'), ('AMF', '前卫'), ('lwm', '左边中场'), ('lm', '左中场'), ('lcm', '左中中场'), ('cm', '中场'), ('lwm', '右边中场'), ('lm', '右中场'), ('lcm', '右中中场'), ('OMF', '前腰'), ('wf', '边锋'), ('lwf', '左边锋'), ('lf', '左前锋'), ('ls', '左中锋'), ('cf', '中锋'), ('rs', '右中锋'), ('rf', '右前锋'), ('rwf', '右边锋'), ('ss', '影子前锋')], max_length=5, null=True, verbose_name='常踢位置'),
        ),
    ]
